#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DOCS_DIR=$SCRIPT_DIR/../docs
ROOT_DIR=$SCRIPT_DIR/..
LATEX_OPTS="--variable=colorlinks"

for m in $DOCS_DIR/*.md; do 
	p=`echo $m | sed 's/\.md$/.pdf/'`;
	echo "Converting $m to $p";
	pandoc -f markdown_github $LATEX_OPTS -o $p $m
done

for n in $ROOT_DIR/*.md; do
  if [[ "$n" =~ README\.md$ ]]; then
    echo "not converting $n"
  else
    q=`echo $n | sed 's/\.md$/.pdf/'`;
    echo "Converting $n to $q";
    pandoc -f markdown_github $LATEX_OPTS -o $q $n
  fi
done

